### ISSUE TITLE
[BUG] Latest version breaks Hydra

### ISSUE THREAD

**Issue by Tuumke** [linuxserver/docker-nzbhydra2#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
12:24:57.352 [main] DEBUG org.nzbhydra.database.DatabaseRecreation - Determining if database recreation is needed
12:24:57.496 [main] ERROR org.nzbhydra.NzbHydra - An unexpected error occurred during startup
org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:222)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
        at org.h2.engine.Database.getPageStore(Database.java:2659)
        at org.h2.engine.Database.open(Database.java:675)
        at org.h2.engine.Database.openDatabase(Database.java:307)
        at org.h2.engine.Database.<init>(Database.java:301)
        at org.h2.engine.Engine.openSession(Engine.java:74)
        at org.h2.engine.Engine.openSession(Engine.java:192)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
        at org.h2.engine.Engine.createSession(Engine.java:166)
        at org.h2.engine.Engine.createSession(Engine.java:29)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
        at org.h2.Driver.connect(Driver.java:69)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
        at org.nzbhydra.database.DatabaseRecreation.isDatabaseRecreationNotNeeded(DatabaseRecreation.java:91)
        at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:75)
        at org.nzbhydra.NzbHydra.startup(NzbHydra.java:194)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:119)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.IllegalStateException: The write format 2 is larger than the supported format 1, and the file was not opened in read-only mode [1.4.200/5]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:741)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:396)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
        ... 28 common frames omitted
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:222)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
        at org.h2.engine.Database.getPageStore(Database.java:2659)
        at org.h2.engine.Database.open(Database.java:675)
        at org.h2.engine.Database.openDatabase(Database.java:307)
        at org.h2.engine.Database.<init>(Database.java:301)
        at org.h2.engine.Engine.openSession(Engine.java:74)
        at org.h2.engine.Engine.openSession(Engine.java:192)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
        at org.h2.engine.Engine.createSession(Engine.java:166)
        at org.h2.engine.Engine.createSession(Engine.java:29)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
        at org.h2.Driver.connect(Driver.java:69)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
        at org.nzbhydra.database.DatabaseRecreation.isDatabaseRecreationNotNeeded(DatabaseRecreation.java:91)
        at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:75)
        at org.nzbhydra.NzbHydra.startup(NzbHydra.java:194)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:119)
        ... 8 more
Caused by: java.lang.IllegalStateException: The write format 2 is larger than the supported format 1, and the file was not opened in read-only mode [1.4.200/5]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:741)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:396)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
        ... 28 more
2023-01-21 12:24:57,520  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it

```

### Expected Behavior

Works as intended

### Steps To Reproduce

My dockers update overnight to latest version.

### Environment

```markdown
- OS: Ubuntu 20.04.5 LTS
- How docker service was installed:
Following digitalocean manuals: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-22-04
```

### CPU architecture

x86-64

### Docker creation

```bash
In a docker-compose


  hydra:
    image: linuxserver/nzbhydra2:latest
    container_name: hydra
    restart: unless-stopped
    networks:
      t2_proxy:
        ipv4_address: ${T2_PROXY:-192.168.90}.9
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DOCKERDIR}/nzbhydra:/config
      - ${DOCKERDIR}/downloads:/downloads
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      - traefik.enable=true
      - traefik.http.routers.hydra-rtr.entrypoints=https
      - traefik.http.routers.hydra-rtr.rule=Host(`nzbhydra.$DOMAINNAME`)
      - traefik.http.routers.hydra-rtr.tls.certresolver=dns-cloudflare
      - traefik.http.routers.hydra-rtr.middlewares=chain-authelia@file
      - traefik.http.routers.hydra-rtr.service=hydra-svc
      - traefik.http.services.hydra-svc.loadbalancer.server.port=5076
      - "com.centurylinklabs.watchtower.scope=mainstack"
```
```


### Container logs

```bash
12:31:34.646 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing to file /config/nzbhydra.yml
12:31:34.680 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing config took 199ms
12:31:34.681 [main] DEBUG org.nzbhydra.NzbHydra - Setting property browser.disabled to value true
12:31:34.698 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.host to 0.0.0.0
12:31:34.698 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.port to 5076
12:31:34.698 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.urlBase to /
12:31:34.699 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.ssl to false
12:31:34.699 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseCompactTime to 15000
12:31:34.699 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseRetentionTime to 1000
12:31:34.699 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseWriteDelay to 5000
12:31:34.699 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.consolelevel to INFO
12:31:34.699 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logfilelevel to INFO
12:31:34.699 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logMaxHistory to 30
12:31:34.788 [main] DEBUG org.nzbhydra.database.DatabaseRecreation - Determining if database recreation is needed
12:31:34.924 [main] ERROR org.nzbhydra.NzbHydra - An unexpected error occurred during startup
org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:222)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
        at org.h2.engine.Database.getPageStore(Database.java:2659)
        at org.h2.engine.Database.open(Database.java:675)
        at org.h2.engine.Database.openDatabase(Database.java:307)
        at org.h2.engine.Database.<init>(Database.java:301)
        at org.h2.engine.Engine.openSession(Engine.java:74)
        at org.h2.engine.Engine.openSession(Engine.java:192)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
        at org.h2.engine.Engine.createSession(Engine.java:166)
        at org.h2.engine.Engine.createSession(Engine.java:29)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
        at org.h2.Driver.connect(Driver.java:69)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
        at org.nzbhydra.database.DatabaseRecreation.isDatabaseRecreationNotNeeded(DatabaseRecreation.java:91)
        at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:75)
        at org.nzbhydra.NzbHydra.startup(NzbHydra.java:194)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:119)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.IllegalStateException: The write format 2 is larger than the supported format 1, and the file was not opened in read-only mode [1.4.200/5]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:741)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:396)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
        ... 28 common frames omitted
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:222)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
        at org.h2.engine.Database.getPageStore(Database.java:2659)
        at org.h2.engine.Database.open(Database.java:675)
        at org.h2.engine.Database.openDatabase(Database.java:307)
        at org.h2.engine.Database.<init>(Database.java:301)
        at org.h2.engine.Engine.openSession(Engine.java:74)
        at org.h2.engine.Engine.openSession(Engine.java:192)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
        at org.h2.engine.Engine.createSession(Engine.java:166)
        at org.h2.engine.Engine.createSession(Engine.java:29)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
        at org.h2.Driver.connect(Driver.java:69)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
        at org.nzbhydra.database.DatabaseRecreation.isDatabaseRecreationNotNeeded(DatabaseRecreation.java:91)
        at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:75)
        at org.nzbhydra.NzbHydra.startup(NzbHydra.java:194)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:119)
        ... 8 more
Caused by: java.lang.IllegalStateException: The write format 2 is larger than the supported format 1, and the file was not opened in read-only mode [1.4.200/5]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:741)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:396)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
        ... 28 more
2023-01-21 12:31:34,958  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
Logging wrapper output to /config/logs/wrapper.log
2023-01-21 12:31:35,103  INFO - Determined java version as '17' from version string 'openjdk version "17.0.5" 2022-10-18'
2023-01-21 12:31:35,104  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Dspring.output.ansi.enabled=ALWAYS -jar /app/nzbhydra2/bin/lib/core-4.7.6-exec.jar --nobrowser --datafolder /config in folder /app/nzbhydra2/bin
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
12:31:36.275 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep010to011.class]
12:31:36.280 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Ignored because not a concrete top-level class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep.class]
12:31:36.281 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep003to004.class]
12:31:36.281 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep015to016.class]
12:31:36.281 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep004to005.class]
12:31:36.282 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep007to008.class]
12:31:36.282 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep006to007.class]
12:31:36.282 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep008to009.class]
12:31:36.282 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep009to010.class]
12:31:36.282 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep011to012.class]
12:31:36.283 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep012to013.class]
12:31:36.283 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep014to015.class]
12:31:36.283 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep013to014.class]
12:31:36.284 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep016to017.class]
12:31:36.284 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep017to018.class]
12:31:36.284 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep018to019.class]
12:31:36.284 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep005to006.class]
12:31:36.495 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing to file /config/nzbhydra.yml
12:31:36.539 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing config took 212ms
12:31:36.539 [main] DEBUG org.nzbhydra.NzbHydra - Setting property browser.disabled to value true
12:31:36.553 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.host to 0.0.0.0
12:31:36.554 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.port to 5076
12:31:36.554 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.urlBase to /
12:31:36.554 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.ssl to false
12:31:36.554 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseCompactTime to 15000
12:31:36.554 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseRetentionTime to 1000
12:31:36.554 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseWriteDelay to 5000
12:31:36.554 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.consolelevel to INFO
12:31:36.554 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logfilelevel to INFO
12:31:36.554 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logMaxHistory to 30
12:31:36.675 [main] DEBUG org.nzbhydra.database.DatabaseRecreation - Determining if database recreation is needed
12:31:36.817 [main] ERROR org.nzbhydra.NzbHydra - An unexpected error occurred during startup
org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:222)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
        at org.h2.engine.Database.getPageStore(Database.java:2659)
        at org.h2.engine.Database.open(Database.java:675)
        at org.h2.engine.Database.openDatabase(Database.java:307)
        at org.h2.engine.Database.<init>(Database.java:301)
        at org.h2.engine.Engine.openSession(Engine.java:74)
        at org.h2.engine.Engine.openSession(Engine.java:192)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
        at org.h2.engine.Engine.createSession(Engine.java:166)
        at org.h2.engine.Engine.createSession(Engine.java:29)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
        at org.h2.Driver.connect(Driver.java:69)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
        at org.nzbhydra.database.DatabaseRecreation.isDatabaseRecreationNotNeeded(DatabaseRecreation.java:91)
        at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:75)
        at org.nzbhydra.NzbHydra.startup(NzbHydra.java:194)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:119)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.IllegalStateException: The write format 2 is larger than the supported format 1, and the file was not opened in read-only mode [1.4.200/5]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:741)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:396)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
        ... 28 common frames omitted
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:222)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
        at org.h2.engine.Database.getPageStore(Database.java:2659)
        at org.h2.engine.Database.open(Database.java:675)
        at org.h2.engine.Database.openDatabase(Database.java:307)
        at org.h2.engine.Database.<init>(Database.java:301)
        at org.h2.engine.Engine.openSession(Engine.java:74)
        at org.h2.engine.Engine.openSession(Engine.java:192)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
        at org.h2.engine.Engine.createSession(Engine.java:166)
        at org.h2.engine.Engine.createSession(Engine.java:29)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
        at org.h2.Driver.connect(Driver.java:69)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
        at org.nzbhydra.database.DatabaseRecreation.isDatabaseRecreationNotNeeded(DatabaseRecreation.java:91)
        at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:75)
        at org.nzbhydra.NzbHydra.startup(NzbHydra.java:194)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:119)
        ... 8 more
Caused by: java.lang.IllegalStateException: The write format 2 is larger than the supported format 1, and the file was not opened in read-only mode [1.4.200/5]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:741)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:396)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
        ... 28 more
2023-01-21 12:31:36,862  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
Logging wrapper output to /config/logs/wrapper.log
2023-01-21 12:31:36,981  INFO - Determined java version as '17' from version string 'openjdk version "17.0.5" 2022-10-18'
2023-01-21 12:31:36,982  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Dspring.output.ansi.enabled=ALWAYS -jar /app/nzbhydra2/bin/lib/core-4.7.6-exec.jar --nobrowser --datafolder /config in folder /app/nzbhydra2/bin
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
12:31:38.174 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep010to011.class]
12:31:38.179 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Ignored because not a concrete top-level class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep.class]
12:31:38.179 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep003to004.class]
12:31:38.179 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep015to016.class]
12:31:38.179 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep004to005.class]
12:31:38.181 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep007to008.class]
12:31:38.181 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep006to007.class]
12:31:38.181 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep008to009.class]
12:31:38.181 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep009to010.class]
12:31:38.182 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep011to012.class]
12:31:38.182 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep012to013.class]
12:31:38.183 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep014to015.class]
12:31:38.183 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep013to014.class]
12:31:38.183 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep016to017.class]
12:31:38.184 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep017to018.class]
12:31:38.184 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep018to019.class]
12:31:38.184 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-4.7.6-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep005to006.class]
12:31:38.384 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing to file /config/nzbhydra.yml
12:31:38.417 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing config took 187ms
12:31:38.417 [main] DEBUG org.nzbhydra.NzbHydra - Setting property browser.disabled to value true
12:31:38.428 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.host to 0.0.0.0
12:31:38.429 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.port to 5076
12:31:38.429 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.urlBase to /
12:31:38.429 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.ssl to false
12:31:38.429 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseCompactTime to 15000
12:31:38.429 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseRetentionTime to 1000
12:31:38.429 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseWriteDelay to 5000
12:31:38.429 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.consolelevel to INFO
12:31:38.429 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logfilelevel to INFO
12:31:38.429 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logMaxHistory to 30
12:31:38.529 [main] DEBUG org.nzbhydra.database.DatabaseRecreation - Determining if database recreation is needed
12:31:38.681 [main] ERROR org.nzbhydra.NzbHydra - An unexpected error occurred during startup
org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:222)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
        at org.h2.engine.Database.getPageStore(Database.java:2659)
        at org.h2.engine.Database.open(Database.java:675)
        at org.h2.engine.Database.openDatabase(Database.java:307)
        at org.h2.engine.Database.<init>(Database.java:301)
        at org.h2.engine.Engine.openSession(Engine.java:74)
        at org.h2.engine.Engine.openSession(Engine.java:192)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
        at org.h2.engine.Engine.createSession(Engine.java:166)
        at org.h2.engine.Engine.createSession(Engine.java:29)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
        at org.h2.Driver.connect(Driver.java:69)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
        at org.nzbhydra.database.DatabaseRecreation.isDatabaseRecreationNotNeeded(DatabaseRecreation.java:91)
        at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:75)
        at org.nzbhydra.NzbHydra.startup(NzbHydra.java:194)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:119)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.IllegalStateException: The write format 2 is larger than the supported format 1, and the file was not opened in read-only mode [1.4.200/5]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:741)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:396)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
        ... 28 common frames omitted
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:222)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
        at org.h2.engine.Database.getPageStore(Database.java:2659)
        at org.h2.engine.Database.open(Database.java:675)
        at org.h2.engine.Database.openDatabase(Database.java:307)
        at org.h2.engine.Database.<init>(Database.java:301)
        at org.h2.engine.Engine.openSession(Engine.java:74)
        at org.h2.engine.Engine.openSession(Engine.java:192)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
        at org.h2.engine.Engine.createSession(Engine.java:166)
        at org.h2.engine.Engine.createSession(Engine.java:29)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
        at org.h2.Driver.connect(Driver.java:69)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
        at org.nzbhydra.database.DatabaseRecreation.isDatabaseRecreationNotNeeded(DatabaseRecreation.java:91)
        at org.nzbhydra.database.DatabaseRecreation.runDatabaseScript(DatabaseRecreation.java:75)
        at org.nzbhydra.NzbHydra.startup(NzbHydra.java:194)
        at org.nzbhydra.NzbHydra.main(NzbHydra.java:119)
        ... 8 more
Caused by: java.lang.IllegalStateException: The write format 2 is larger than the supported format 1, and the file was not opened in read-only mode [1.4.200/5]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:741)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:396)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
        ... 28 more
2023-01-21 12:31:38,725  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
Logging wrapper output to /config/logs/wrapper.log
2023-01-21 12:31:38,865  INFO - Determined java version as '17' from version string 'openjdk version "17.0.5" 2022-10-18'
2023-01-21 12:31:38,865  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/logs -Dspring.output.ansi.enabled=ALWAYS -jar /app/nzbhydra2/bin/lib/core-4.7.6-exec.jar --nobrowser --datafolder /config in folder /app/nzbhydra2/bin
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
^C

```
```

**Comment by Tuumke** [comment]
Wen't back to tag 5.0.0 and that works just fine.

**Comment by perfectly-preserved-pie** [comment]
Was having the same error yesterday.
Using [amd64-5.0.4-dev](https://hub.docker.com/layers/linuxserver/nzbhydra2/amd64-5.0.4-dev/images/sha256-a726ddc179fbf720aa93318e2d541c976ed446d485977ff45ab3ae392237fa2a?context=explore) now and it works again.

**Comment by thespad** [comment]
There was an issue with the initial release of 5.0.0 that broken some installs so we had to roll back to 4.x, which broke any installs that had successfully upgraded.

Everything should be fixed if you pull the latest image.

**Comment by Tuumke** [comment]
I had the same issue going back from 5.0.0 to latest. This isn't solved for me

-edit-
So dumb, forgot to pull. Works again!
